[project]
name = "gcp-python-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Augusto Giavedoni", email = "58192738+augustogiavedoni@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
gcp-python-api = "gcp_python_api:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "gcp_python_api.main:app"

[dependency-groups]
dev = [
    "httpx2>=2.13.1",
    "pytest>=9.1.1",
]
